application: connexusssar
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /test.*
  login: admin
  script: gaeunit.py
- url: /stylesheets
  static_dir: stylesheets
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /js/images
  static_dir: /js/images
- url: /.*
  script: connexus.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: "1.2"
