application: connexusssar
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /test.*
  login: admin
  script: gaeunit.py
- url: /.*
  script: connexus.application
- url: /js
  static_dir: js

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: "1.2"
